# -*- coding: utf-8 -*-
"""script_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AwuvvjeufDvlSM8tPg2RsR7fDZcDZ-5e
"""

#enter a number and print all prime numbers till that number
n = 10
prime_number = []

for i in range(2, n + 1):
	for j in range(2, int(i ** 0.5) + 1):
 		if i%j == 0:
 			break
	else:
		prime_number.append(i)

print(prime_number)

