# -*- coding: utf-8 -*-
"""script_ 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AwuvvjeufDvlSM8tPg2RsR7fDZcDZ-5e
"""

#enter 2 numbers and print all prime numbers between them. 
lower_num=int(input("enter the lower range: ")) 
upper_num=int(input("enter the upper range: ")) 

for num in range(lower_num,upper_num +1): 
  if num>1: 
    for i in range(2,num): 
        if (num%i)==0: 
            break 
    else: 
      print(num)